using HarmonyLib;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Helpers;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Logging;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.TextEffects;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace SlayTheSpire2Mod.CardEditor;

[HarmonyPatch(typeof(CardModel), "get_Title")]
public static class CardModel_get_Title_CreatedCards_Patch
{
	public static bool Prefix(CardModel __instance, ref string __result)
	{
		if (__instance is not CardEditorCreatedCardBase)
		{
			return true;
		}

		if (CardEditorExtraEffects.TryGetDynamicIdentitySource(__instance, out CardModel identitySource))
		{
			__result = identitySource.Title;
			return false;
		}

		string title = CardEditorCreatedCardsStore.GetTitleForCard(__instance.Id);
		if (!__instance.IsUpgraded)
		{
			__result = title;
			return false;
		}

		if (__instance.MaxUpgradeLevel > 1)
		{
			__result = $"{title}+{__instance.GetSafeCurrentUpgradeLevel()}";
			return false;
		}

		__result = title + "+";
		return false;
	}
}

// NOTE: GetDescriptionForPile patch moved to CardEditorMod.cs to consolidate with the Postfix
// [HarmonyPatch(typeof(CardModel), nameof(CardModel.GetDescriptionForPile), typeof(PileType), typeof(Creature))]
// public static class CardModel_GetDescriptionForPile_CreatedCards_Patch - DISABLED

[HarmonyPatch(typeof(CardModel), nameof(CardModel.GetDescriptionForUpgradePreview))]
public static class CardModel_GetDescriptionForUpgradePreview_CreatedCards_Patch
{
	[HarmonyPriority(Priority.First)]
	public static bool Prefix(CardModel __instance, ref string __result)
	{
		if (__instance is not CardEditorCreatedCardBase)
		{
			return true;
		}

		if (CardEditorExtraEffects.TryGetDynamicIdentitySource(__instance, out CardModel identitySource))
		{
			__result = identitySource.GetDescriptionForUpgradePreview();
			return false;
		}

		__result = CreatedCardTextBuilder.Build(__instance, __instance.GetSafeCurrentTarget(), isUpgradePreview: true);
		CardEditorUpgradeDeltaDebugLog.LogDescription("Description.CreatedGetDescriptionForUpgradePreview.prefix", __instance, PileType.None, isUpgradePreview: true, __result);
		return false;
	}
}

internal static class CreatedCardTextBuilder
{
	private static readonly LocString _keywordPeriod = new LocString("card_keywords", "PERIOD");

	public static string Build(CardModel card, Creature? target, bool isUpgradePreview)
	{
		if (card == null)
		{
			return string.Empty;
		}

		// Custom text override — user-written text replaces auto-generated description
		bool wantsUpgradedText = isUpgradePreview || card.IsUpgraded;
		if (wantsUpgradedText)
		{
			string? customUpgraded = CardEditorCreatedCardsStore.GetCustomTextUpgraded(card.Id);
			if (customUpgraded != null)
			{
				string autoDescription = BuildAutoGeneratedDescription(card, target, isUpgradePreview);
				IReadOnlyList<string> fallbackLiveNumbers = CardEditorExtraEffects.GetLiveNumberFallbackTokensForDescription(card, isUpgradePreview);
				IReadOnlyDictionary<string, string> stableLiveNumbers = CardEditorExtraEffects.GetStableLiveNumberTokensForDescription(card, isUpgradePreview);
				string syncedText = CardEditorDescriptionNumberHighlighter.ApplyLiveNumbersAndManagedLinesFromReference(
					customUpgraded,
					autoDescription,
					fallbackLiveNumbers,
					stableLiveNumbers);
				string rendered = CardEditorVanillaKeywordSupport.FormatDescription(card, syncedText, target, isUpgradePreview);
				string? baseCustom = CardEditorCreatedCardsStore.GetCustomText(card.Id);
				return isUpgradePreview ? ApplyUpgradePreviewNumericHighlight(card, target, rendered, baseCustom) : rendered;
			}
		}

		string? customText = CardEditorCreatedCardsStore.GetCustomText(card.Id);
		if (customText != null)
		{
			string autoDescription = BuildAutoGeneratedDescription(card, target, isUpgradePreview);
			IReadOnlyList<string> fallbackLiveNumbers = CardEditorExtraEffects.GetLiveNumberFallbackTokensForDescription(card, isUpgradePreview);
			IReadOnlyDictionary<string, string> stableLiveNumbers = CardEditorExtraEffects.GetStableLiveNumberTokensForDescription(card, isUpgradePreview);
			string syncedText = CardEditorDescriptionNumberHighlighter.ApplyLiveNumbersAndManagedLinesFromReference(
				customText,
				autoDescription,
				fallbackLiveNumbers,
				stableLiveNumbers);
			string rendered = CardEditorVanillaKeywordSupport.FormatDescription(card, syncedText, target, isUpgradePreview);
			return isUpgradePreview ? ApplyUpgradePreviewNumericHighlight(card, target, rendered, customText) : rendered;
		}

		return BuildAutoGeneratedDescription(card, target, isUpgradePreview);
	}

	internal static string BuildAutoGeneratedDescription(CardModel card, Creature? target, bool isUpgradePreview)
	{
		List<string> lines = new List<string>();

		bool hasInlineEffectSources = CardEditorExtraEffects.GetEffectsForDescription(card, isUpgradePreview)
			.Any(e => e != null && e.Kind == CardExtraEffectKind.RunEffectSourceCard);

		List<string> sourceLines = new List<string>();
		if (!hasInlineEffectSources)
		{
			List<string> sourceDescriptions = CardEditorCreatedCardEffectSourceSupport.GetEffectSourceDescriptions(card, target, isUpgradePreview);
			foreach (string sourceDescription in sourceDescriptions)
			{
				if (!string.IsNullOrWhiteSpace(sourceDescription))
				{
					string fixedDesc = sourceDescription;
					TargetTypeOverrideDescriptionFix.TryFix(card, ref fixedDesc);
					sourceLines.AddRange(fixedDesc.Split('\n').Where(l => !string.IsNullOrEmpty(l)));
				}
			}
		}

		List<string> customLines = new List<string>();
		string customDescription = string.Empty;
		CardEditorExtraEffects.TryAppendDescription(card, ref customDescription, target, isUpgradePreview);
		if (!string.IsNullOrWhiteSpace(customDescription))
		{
			customDescription = CardEditorVanillaKeywordSupport.FormatDescription(customDescription);
			customLines.AddRange(customDescription.Split('\n').Where(l => !string.IsNullOrEmpty(l)));
		}

		if (CardEditorCreatedCardsStore.GetEffectSourcePlacement(card.Id) == CardEditorEffectSourcePlacement.AfterCustomEffects)
		{
			lines.AddRange(customLines);
			lines.AddRange(sourceLines);
		}
		else
		{
			lines.AddRange(sourceLines);
			lines.AddRange(customLines);
		}

		try
		{
			LocString? enchantText = card.Enchantment?.DynamicExtraCardText;
			if (enchantText != null)
			{
				lines.Add("[purple]" + enchantText.GetFormattedText() + "[/purple]");
			}
		}
		catch
		{
		}

		try
		{
			LocString? afflictText = card.Affliction?.DynamicExtraCardText;
			if (afflictText != null)
			{
				lines.Add("[purple]" + afflictText.GetFormattedText() + "[/purple]");
			}
		}
		catch
		{
		}

		HashSet<CardKeyword> keywords = new HashSet<CardKeyword>(card.Keywords);
		foreach (CardKeyword cardKeyword in CardKeywordOrder.beforeDescription)
		{
			bool include = cardKeyword switch
			{
				CardKeyword.Sly => card.IsSlyThisTurn,
				CardKeyword.Retain => card.ShouldRetainThisTurn,
				_ => keywords.Contains(cardKeyword),
			};
			if (include)
			{
				lines.Insert(0, GetKeywordCardText(cardKeyword));
			}
		}

		int enchantedReplayCount = card.GetEnchantedReplayCount();
		if (enchantedReplayCount > 0)
		{
			try
			{
				LocString replay = new LocString("static_hover_tips", "REPLAY.extraText");
				replay.Add("Times", enchantedReplayCount);
				lines.Add(replay.GetFormattedText() ?? string.Empty);
			}
			catch
			{
			}
		}

		foreach (CardKeyword cardKeyword in CardKeywordOrder.afterDescription)
		{
			if (keywords.Contains(cardKeyword))
			{
				lines.Add(GetKeywordCardText(cardKeyword));
			}
		}

		return string.Join('\n', lines.Where(l => !string.IsNullOrEmpty(l)));
	}

	private static string GetKeywordCardText(CardKeyword keyword)
	{
		try
		{
			string prefix = StringHelper.Slugify(keyword.ToString());
			LocString title = new LocString("card_keywords", prefix + ".title");
			return "[gold]" + title.GetFormattedText() + "[/gold]" + _keywordPeriod.GetRawText();
		}
		catch
		{
			return "[gold]" + keyword + "[/gold].";
		}
	}

	private static string ApplyUpgradePreviewNumericHighlight(CardModel card, Creature? target, string upgradedDescription, string? baseDescriptionOverride = null)
	{
		if (card == null || string.IsNullOrWhiteSpace(upgradedDescription))
		{
			return upgradedDescription;
		}

		string? baseDescription = TryBuildBaseDescription(card, target, baseDescriptionOverride);
		if (string.IsNullOrWhiteSpace(baseDescription) || string.Equals(baseDescription, upgradedDescription, System.StringComparison.Ordinal))
		{
			return upgradedDescription;
		}

		return CardEditorDescriptionNumberHighlighter.HighlightChangedNumbers(baseDescription, upgradedDescription);
	}

	private static string? TryBuildBaseDescription(CardModel upgradedCard, Creature? target, string? baseDescriptionOverride)
	{
		try
		{
			CardModel baseCard = ModelDb.GetById<CardModel>(upgradedCard.Id).ToMutable();
			MegaCrit.Sts2.Core.Entities.Players.Player? owner = upgradedCard.TryGetOwner();
			if (owner != null && baseCard.TryGetOwner() == null)
			{
				baseCard.Owner = owner;
			}

			if (!string.IsNullOrWhiteSpace(baseDescriptionOverride))
			{
				string autoDescription = BuildAutoGeneratedDescription(baseCard, target, isUpgradePreview: false);
				IReadOnlyList<string> fallbackLiveNumbers = CardEditorExtraEffects.GetLiveNumberFallbackTokensForDescription(baseCard, isUpgradePreview: false);
				IReadOnlyDictionary<string, string> stableLiveNumbers = CardEditorExtraEffects.GetStableLiveNumberTokensForDescription(baseCard, isUpgradePreview: false);
				string syncedText = CardEditorDescriptionNumberHighlighter.ApplyLiveNumbersAndManagedLinesFromReference(
					baseDescriptionOverride,
					autoDescription,
					fallbackLiveNumbers,
					stableLiveNumbers);
				return CardEditorVanillaKeywordSupport.FormatDescription(baseCard, syncedText, target, isUpgradePreview: false);
			}

			return Build(baseCard, target, isUpgradePreview: false);
		}
		catch
		{
			return null;
		}
	}

	private static string HighlightChangedNumbersInLine(string baseLine, string upgradedLine)
	{
		List<string> baseTokens = ExtractVisibleNumberTokens(baseLine);
		StringBuilder builder = new StringBuilder(upgradedLine.Length + 24);
		int tokenIndex = 0;
		int highlightDepth = 0;
		int imageDepth = 0;

		for (int i = 0; i < upgradedLine.Length;)
		{
			if (upgradedLine[i] == '[')
			{
				int tagEnd = upgradedLine.IndexOf(']', i);
				if (tagEnd < 0)
				{
					builder.Append(upgradedLine.AsSpan(i));
					break;
				}

				string tag = upgradedLine.Substring(i, tagEnd - i + 1);
				builder.Append(tag);
				UpdateInlineTagState(tag, ref highlightDepth, ref imageDepth);
				i = tagEnd + 1;
				continue;
			}

			if (highlightDepth == 0 && imageDepth == 0 && TryReadNumericToken(upgradedLine, i, out int tokenEndExclusive))
			{
				string token = upgradedLine.Substring(i, tokenEndExclusive - i);
				string? baseToken = tokenIndex < baseTokens.Count ? baseTokens[tokenIndex] : null;
				int comparison = GetUpgradeHighlightComparison(baseToken, token);
				if (comparison != 0)
				{
					builder.Append(StsTextUtilities.HighlightChangeText(token, comparison));
				}
				else
				{
					builder.Append(token);
				}

				i = tokenEndExclusive;
				tokenIndex++;
				continue;
			}

			builder.Append(upgradedLine[i]);
			i++;
		}

		return builder.ToString();
	}

	private static List<string> ExtractVisibleNumberTokens(string line)
	{
		List<string> tokens = new List<string>();
		int highlightDepth = 0;
		int imageDepth = 0;
		for (int i = 0; i < line.Length;)
		{
			if (line[i] == '[')
			{
				int tagEnd = line.IndexOf(']', i);
				if (tagEnd < 0)
				{
					break;
				}

				string tag = line.Substring(i, tagEnd - i + 1);
				UpdateInlineTagState(tag, ref highlightDepth, ref imageDepth);
				i = tagEnd + 1;
				continue;
			}

			if (highlightDepth == 0 && imageDepth == 0 && TryReadNumericToken(line, i, out int tokenEndExclusive))
			{
				tokens.Add(line.Substring(i, tokenEndExclusive - i));
				i = tokenEndExclusive;
				continue;
			}

			i++;
		}

		return tokens;
	}

	private static bool TryReadNumericToken(string text, int start, out int endExclusive)
	{
		endExclusive = start;
		if (start < 0 || start >= text.Length)
		{
			return false;
		}

		int cursor = start;
		if ((text[cursor] == '+' || text[cursor] == '-') && cursor + 1 < text.Length && char.IsDigit(text[cursor + 1]))
		{
			cursor++;
		}

		if (cursor >= text.Length || !char.IsDigit(text[cursor]))
		{
			return false;
		}

		while (cursor < text.Length && char.IsDigit(text[cursor]))
		{
			cursor++;
		}

		if (cursor < text.Length
			&& text[cursor] == '.'
			&& cursor + 1 < text.Length
			&& char.IsDigit(text[cursor + 1]))
		{
			cursor++;
			while (cursor < text.Length && char.IsDigit(text[cursor]))
			{
				cursor++;
			}
		}

		endExclusive = cursor;
		return true;
	}

	private static int GetUpgradeHighlightComparison(string? baseToken, string upgradedToken)
	{
		if (string.IsNullOrWhiteSpace(upgradedToken))
		{
			return 0;
		}

		if (string.IsNullOrWhiteSpace(baseToken))
		{
			return 1;
		}

		if (string.Equals(baseToken, upgradedToken, System.StringComparison.Ordinal))
		{
			return 0;
		}

		if (decimal.TryParse(baseToken, NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out decimal baseValue)
			&& decimal.TryParse(upgradedToken, NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out decimal upgradedValue))
		{
			return upgradedValue.CompareTo(baseValue);
		}

		return 1;
	}

	private static void UpdateInlineTagState(string tag, ref int highlightDepth, ref int imageDepth)
	{
		if (tag.Equals("[green]", System.StringComparison.OrdinalIgnoreCase)
			|| tag.Equals("[red]", System.StringComparison.OrdinalIgnoreCase))
		{
			highlightDepth++;
		}
		else if (tag.Equals("[/green]", System.StringComparison.OrdinalIgnoreCase)
			|| tag.Equals("[/red]", System.StringComparison.OrdinalIgnoreCase))
		{
			highlightDepth = highlightDepth > 0 ? highlightDepth - 1 : 0;
		}
		else if (tag.StartsWith("[img", System.StringComparison.OrdinalIgnoreCase))
		{
			imageDepth++;
		}
		else if (tag.Equals("[/img]", System.StringComparison.OrdinalIgnoreCase))
		{
			imageDepth = imageDepth > 0 ? imageDepth - 1 : 0;
		}
	}
}
